const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"单位管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryDanwei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"会议室类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuiyishi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"会议室预约类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuiyishiYuyue"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"信访目的管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLaifangdengjiMudi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公文年号管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNianhao"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公文管理",
                        "menuJump":"列表",
                        "tableName":"gongwen"
                    }
                ],
                "menu":"公文管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"会议室管理",
                        "menuJump":"列表",
                        "tableName":"huiyishi"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"会议室预约管理",
                        "menuJump":"列表",
                        "tableName":"huiyishiYuyue"
                    }
                ],
                "menu":"会议室管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"来访登记管理",
                        "menuJump":"列表",
                        "tableName":"laifangdengji"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"信访督办管理",
                        "menuJump":"列表",
                        "tableName":"xinfangduban"
                    }
                ],
                "menu":"来访管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"公文管理",
                        "menuJump":"列表",
                        "tableName":"gongwen"
                    }
                ],
                "menu":"公文管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"会议室管理",
                        "menuJump":"列表",
                        "tableName":"huiyishi"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"会议室预约管理",
                        "menuJump":"列表",
                        "tableName":"huiyishiYuyue"
                    }
                ],
                "menu":"会议室管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"来访登记管理",
                        "menuJump":"列表",
                        "tableName":"laifangdengji"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"信访督办管理",
                        "menuJump":"列表",
                        "tableName":"xinfangduban"
                    }
                ],
                "menu":"来访管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
